### ISSUE TITLE
KeyError: 'Will'

### ISSUE THREAD

**Issue by sinclchris** [sinclchris/Maelstrom-character-creator#6]
Traceback (most recent call last):

  File "C:\Users\cex\OneDrive\Projects\Python\Maelstrom Character Creator\Main.py", line 549, in <module>
    SecondCareer=CareerLoop(SecondCareer[0][1],SecondCareer[3][1],SecondCareer[1][1],SecondCareer[2][2])

  File "C:\Users\cex\OneDrive\Projects\Python\Maelstrom Character Creator\Main.py", line 293, in CareerLoop
    ExitAttributes = AttributesGen(attributes,careername1)

  File "C:\Users\cex\OneDrive\Projects\Python\Maelstrom Character Creator\Main.py", line 341, in AttributesGen
    X=AttributesMap[Characteristic[i]]

KeyError: 'Will'

**Comment by sinclchris** [comment]
Solved with version 9 update.
